let
  Source = Sql.Database("localhost", "NYC_Taxi"), 
  dbo_payment_type = Source{[Schema = "dbo", Item = "payment_type"]}[Data], 
  AddPrefixSuffix = Table.TransformColumns(
    dbo_payment_type, 
    {{"PaymentType", each "PMT: " & _ & " Payment", type text}}
  )
in
  AddPrefixSuffix
