let
    Source = Csv.Document(File.Contents("C:\NYC Taxi\trip_data_green.csv"),[Delimiter=",", Columns=20, Encoding=1252, QuoteStyle=QuoteStyle.None]),
    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
    TextBefore = Table.TransformColumns(PromotedHeaders, {{"lpep_pickup_datetime", each Text.BeforeDelimiter(_, "-", 1), type text}})
in
    TextBefore
