let
  Source = Sql.Database("localhost", "NYC_Taxi"), 
  dbo_payment_type = Source{[Schema = "dbo", Item = "payment_type"]}[Data], 
  LowercaseText = Table.TransformColumns(
    dbo_payment_type, 
    {{"PaymentType", Text.Lower, type text}}, 
    null, 
    MissingField.Ignore
  )
in
  LowercaseText
