let
  Source = Csv.Document(
    File.Contents("C:\NYC Taxi\trip_data_green.csv"), 
    [Delimiter = ",", Columns = 20, Encoding = 1252, QuoteStyle = QuoteStyle.None]
  ), 
  PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars = true]), 
  ChangedDateTime = Table.TransformColumnTypes(
    PromotedHeaders, 
    {{"lpep_pickup_datetime", type datetime}}
  ), 
  ChangedDateOnly = Table.TransformColumnTypes(
    ChangedDateTime, 
    {{"lpep_pickup_datetime", type date}}
  )
in
  ChangedDateOnly
