let
  Source = Sql.Database("localhost", "NYC_Taxi"), 
  TripData = Source{[Schema = "dbo", Item = "trip_data_yellow"]}[Data], 
  FilterStart = (Date.Year(RangeStart) * 10000)
    + (Date.Month(RangeStart) * 100)
    + Date.Day(RangeStart), 
  FilterEnd = (Date.Year(RangeEnd) * 10000) 
    + (Date.Month(RangeEnd) * 100) 
    + Date.Day(RangeEnd), 
  IncrementalFilter = Table.SelectRows(TripData, 
    each [tpep_pickup_datetime] >= FilterStart 
    and [tpep_pickup_datetime] <= FilterEnd
  )
in
  IncrementalFilter
